services:
  streamlit-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./.env:/app/.env
      - ./data:/app/data
    networks:
      - app-network
    depends_on:
      - relay-server
    environment:
      - IN_DOCKER=true

  relay-server:
    build:
      context: .
      dockerfile: Dockerfile.relay
    ports:
      - "5000:5000"
    volumes:
      - ./.env:/app/.env
      - ./data:/app/data
    networks:
      - app-network
    environment:
      - IN_DOCKER=true

networks:
  app-network:
    driver: bridge