import streamlit as st
import datetime
from utils.constants import CHAT_DEFAULT
from utils.pdf_utils import pdf_to_text
from utils.chat_utils import update_key, get_text_to_text, export_conversations, import_conversations
from utils import check_model
from api import gemini, cloudflare, cohere, openrouter, groq

# Initialize session state variables
SESSION_DEFAULTS = {
    "messages": CHAT_DEFAULT.copy(),
    "messages_2": CHAT_DEFAULT.copy(),
    "system_prompt": "",
    "system_prompt_2": "",
    "chat_uploader_key": 0,
    "pdf_uploader_key": 131072,
    "usage_info": {},
    "max_tokens": 8192,
    "temperature": 0.5,
    "enable_streaming": True,
    "edit_mode": False,
    "comparison_mode": False,
    "model_provider": "Local Model",
    "model_provider_2": "Google Gemini",
    "local_model": None,
    "gemini_model": "gemini-1.5-pro",
    "gemini_model_2": "gemini-1.5-pro",
    "cloudflare_model": "Llama 4 Scout 17B 16E Instruct",
    "cloudflare_model_2": "Llama 4 Scout 17B 16E Instruct",
    "cohere_model": "Command R+",
    "cohere_model_2": "Command R+",
    "openrouter_model": "NVDA Llama 3.1 Nemotron Ultra 253B V1",
    "openrouter_model_2": "NVDA Llama 3.1 Nemotron Ultra 253B V1",
    "groq_model": "Llama 4 Maverick 17B 128E Instruct",
    "groq_model_2": "Llama 4 Maverick 17B 128E Instruct"
}

# Initialize session state variables
for key, default_value in SESSION_DEFAULTS.items():
    if key not in st.session_state:
        st.session_state[key] = default_value

# Set page config
st.set_page_config(page_title="Text Chat Bot", page_icon="🤖", layout="wide", menu_items={"Report a bug": "mailto:jjy@jimmyn.idv.tw"})
if st.session_state.model_provider == "Local Model":
    st.session_state.local_model = check_model.get_current_model_name()
    if st.session_state.local_model == None:
        st.badge("Local Model is not running. Please check the model server.")
    else:
        st.badge(f"Current AI Model: {st.session_state.local_model}")
elif st.session_state.model_provider == "Google Gemini":
    st.badge(f"Current AI Model: {st.session_state.gemini_model}")
elif st.session_state.model_provider == "Cloudflare Workers AI":
    st.badge(f"Current AI Model: {st.session_state.cloudflare_model}")
elif st.session_state.model_provider == "Cohere":
    st.badge(f"Current AI Model: {st.session_state.cohere_model}")
elif st.session_state.model_provider == "OpenRouter":
    st.badge(f"Current AI Model: {st.session_state.openrouter_model}")
elif st.session_state.model_provider == "Groq":
    st.badge(f"Current AI Model: {st.session_state.groq_model}")

progress_bar = st.empty()

# Sidebar
sidebar = st.sidebar
with sidebar:
    st.session_state.comparison_mode = st.toggle(
            label="Comparison Mode",
            help="Enable comparison mode to generate responses from multiple models simultaneously.",
            value=st.session_state.comparison_mode
        )

# Main Interface
if st.session_state.comparison_mode:
    col1, col2 = st.columns([1, 1])
    with col1:
        st.subheader("Model 1")
        total_messages = len(st.session_state.messages)
        for index, message in enumerate(st.session_state.messages):
            if index == total_messages - 4:
                if st.session_state.edit_mode == True:
                    editor = st.empty()
                    new_message = editor.text_input("Edit last message", value=message["content"])
                    if new_message is not message["content"]:
                        editor.empty()
                        st.session_state.messages[-2]["content"] = new_message
                        del st.session_state.messages[-1]
                        st.session_state.edit_mode = False
                        st.chat_message("user").markdown(new_message)
                        get_text_to_text()
                        st.rerun()
                else:
                    if message["type"] == "PDF":
                        st.chat_message("user").expander(message["file_name"], expanded=False).markdown(message["content"])
                    elif message["role"] != "system":
                        if message.get("reasoning"):
                            st.chat_message("assistant").expander("Reasoning", expanded=False).markdown(message["reasoning"])
                        st.chat_message(message["role"]).markdown(message["content"])
                        if message["role"] == "assistant" and "model" in message:
                            st.caption(f"Generated by: {message['model']}")
            else:
                if message["type"] == "PDF":
                    st.chat_message("user").expander(message["file_name"], expanded=False).markdown(message["content"])
                elif message["role"] != "system":
                    if message.get("reasoning"):
                        st.chat_message("assistant").expander("Reasoning", expanded=False).markdown(message["reasoning"])
                    st.chat_message(message["role"]).markdown(message["content"])
                    if message["role"] == "assistant" and "model" in message:
                        st.caption(f"Generated by: {message['model']}")
    with col2:
        st.subheader("Model 2")
        total_messages = len(st.session_state.messages_2)
        for index, message in enumerate(st.session_state.messages_2):
            if index == total_messages - 4:
                if st.session_state.edit_mode == True:
                    editor = st.empty()
                    new_message = editor.text_input("Edit last message", value=message["content"])
                    if new_message is not message["content"]:
                        editor.empty()
                        st.session_state.messages_2[-2]["content"] = new_message
                        del st.session_state.messages_2[-1]
                        st.session_state.edit_mode = False
                        st.chat_message("user").markdown(new_message)
                        get_text_to_text()
                        st.rerun()
                else:
                    if message["type"] == "PDF":
                        st.chat_message("user").expander(message["file_name"], expanded=False).markdown(message["content"])
                    elif message["role"] != "system":
                        if message.get("reasoning"):
                            st.chat_message("assistant").expander("Reasoning", expanded=False).markdown(message["reasoning"])
                        st.chat_message(message["role"]).markdown(message["content"])
                        if message["role"] == "assistant" and "model" in message:
                            st.caption(f"Generated by: {message['model']}")
            else:
                if message["type"] == "PDF":
                    st.chat_message("user").expander(message["file_name"], expanded=False).markdown(message["content"])
                elif message["role"] != "system":
                    if message.get("reasoning"):
                        st.chat_message("assistant").expander("Reasoning", expanded=False).markdown(message["reasoning"])
                    st.chat_message(message["role"]).markdown(message["content"])
                    if message["role"] == "assistant" and "model" in message:
                        st.caption(f"Generated by: {message['model']}")
else:
    total_messages = len(st.session_state.messages)
    for index, message in enumerate(st.session_state.messages):
        if index == total_messages - 4:
            if st.session_state.edit_mode == True:
                editor = st.empty()
                new_message = editor.text_input("Edit last message", value=message["content"])
                if new_message is not message["content"]:
                    editor.empty()
                    st.session_state.messages[-2]["content"] = new_message
                    del st.session_state.messages[-1]
                    st.session_state.edit_mode = False
                    st.chat_message("user").markdown(new_message)
                    get_text_to_text()
                    st.rerun()
            else:
                if message["type"] == "PDF":
                    st.chat_message("user").expander(message["file_name"], expanded=False).markdown(message["content"])
                elif message["role"] != "system":
                    if message.get("reasoning"):
                        st.chat_message("assistant").expander("Reasoning", expanded=False).markdown(message["reasoning"])
                    st.chat_message(message["role"]).markdown(message["content"])
                    if message["role"] == "assistant" and "model" in message:
                        st.caption(f"Generated by: {message['model']}")
        else:
            if message["type"] == "PDF":
                st.chat_message("user").expander(message["file_name"], expanded=False).markdown(message["content"])
            elif message["role"] != "system":
                if message.get("reasoning"):
                    st.chat_message("assistant").expander("Reasoning", expanded=False).markdown(message["reasoning"])
                st.chat_message(message["role"]).markdown(message["content"])
                if message["role"] == "assistant" and "model" in message:
                    st.caption(f"Generated by: {message['model']}")

# Accept user input
input_container = st.empty()
prompt = input_container.chat_input("Enter your message here...",key=32768)
if prompt:
    st.chat_message("user").markdown(prompt)
    progress_bar = st.progress(0, "Generating response...")
    message_placeholder = st.empty()
    current_date = datetime.datetime.now(datetime.timezone(datetime.timedelta(hours=8))).strftime("%Y-%m-%d %H:%M:%S")
    
    if st.session_state.comparison_mode:
        # Handle system prompts for both models
        if st.session_state.system_prompt:
            if not (len(st.session_state.messages) > 0 and 
                    st.session_state.messages[0].get('role') == 'system' and 
                    st.session_state.messages[0].get('content') == st.session_state.system_prompt):
                st.session_state.messages.append(0, {
                    'role': 'system', 
                    'type': 'message', 
                    'content': st.session_state.system_prompt
                })
        
        if st.session_state.system_prompt_2:
            if not (len(st.session_state.messages_2) > 0 and 
                    st.session_state.messages_2[0].get('role') == 'system' and 
                    st.session_state.messages_2[0].get('content') == st.session_state.system_prompt_2):
                st.session_state.messages_2.insert(0, {
                    'role': 'system', 
                    'type': 'message', 
                    'content': st.session_state.system_prompt_2
                })
        
        # Add date and user message to both conversations
        date_message = {'role': 'system', 'type': 'message', 'content': "Current Date and Time: " + current_date}
        user_message = {'role': 'user', 'type': 'message', 'content': prompt}
        
        st.session_state.messages.extend([date_message, user_message])
        st.session_state.messages_2.extend([date_message.copy(), user_message.copy()])
        
        input_container.empty()
        first_response, second_response = get_text_to_text(progress_bar, message_placeholder)
    else:
        # Original single model logic
        if st.session_state.system_prompt:
            if not (len(st.session_state.messages) > 0 and 
                    st.session_state.messages[0].get('role') == 'system' and 
                    st.session_state.messages[0].get('content') == st.session_state.system_prompt):
                st.session_state.messages.insert(0, {
                    'role': 'system', 
                    'type': 'message', 
                    'content': st.session_state.system_prompt
                })
        
        st.session_state.messages.append({'role': 'system', 'type': 'message', 'content': "Current Date and Time: " + current_date})
        st.session_state.messages.append({'role': 'user', 'type': 'message', 'content': prompt})
        input_container.empty()
        response = get_text_to_text(progress_bar, message_placeholder)
    
    st.rerun()
message_placeholder = st.empty()

with sidebar:
    if st.session_state.comparison_mode:
        model_1, model_2 = st.tabs(["Model 1", "Model 2"])
        with model_1:
            # Add system prompt input
            system_prompt = st.text_area(
                label="System Prompt",
                help="Set a system prompt that will be included at the beginning of each conversation. Leave empty for no system prompt.",
                value=st.session_state.system_prompt,
                placeholder="Example: You are a helpful assistant who specializes in programming...",
                height=100
            )
            # Update session state if the prompt has changed
            if system_prompt != st.session_state.system_prompt:
                st.session_state.system_prompt = system_prompt

            st.session_state.model_provider = st.selectbox(
                label="Model Provider",
                help="Select the AI model provider to use for generating responses.",
                options=["Local Model", "Google Gemini", "Cloudflare Workers AI", "Cohere", "OpenRouter", "Groq"],
                index=["Local Model", "Google Gemini", "Cloudflare Workers AI", "Cohere", "OpenRouter", "Groq"].index(st.session_state.model_provider)
            )
            if st.session_state.model_provider == "Google Gemini":
                st.session_state.gemini_model = st.selectbox(
                    label="Gemini Model",
                    help="Select which Gemini model to use.",
                    options=gemini.models.keys()
                )
            elif st.session_state.model_provider == "Cloudflare Workers AI":
                st.session_state.cloudflare_model = st.selectbox(
                    label="Cloudflare Workers AI Model",
                    help="Select which Cloudflare Workers AI model to use.",
                    options=cloudflare.models.keys()
                )
            elif st.session_state.model_provider == "Cohere":
                st.session_state.cohere_model = st.selectbox(
                    label="Cohere Model",
                    help="Select which Cohere model to use.",
                    options=cohere.models.keys()
                )
            elif st.session_state.model_provider == "OpenRouter":
                st.session_state.openrouter_model = st.selectbox(
                    label="OpenRouter Model",
                    help="Select which OpenRouter model to use.",
                    options=openrouter.models.keys()
                )
            elif st.session_state.model_provider == "Groq":
                st.session_state.groq_model = st.selectbox(
                    label="Groq Model",
                    help="Select which Groq model to use.",
                    options=groq.models.keys()
                )
        with model_2:
            if st.session_state.comparison_mode:
                # Add system prompt input for comparison model
                system_prompt_2 = st.text_area(
                    label="Comparison System Prompt",
                    help="Set a system prompt for the comparison model. Leave empty for no system prompt.",
                    value=st.session_state.system_prompt_2,
                    placeholder="Example: You are a helpful assistant who specializes in programming...",
                    height=100
                )
                providers = [opt for opt in ["Local Model", "Google Gemini", "Cloudflare Workers AI", "Cohere", "OpenRouter", "Groq"] if opt != st.session_state.model_provider]
                st.session_state.model_provider_2 = st.selectbox(
                    label="Comparison Model Provider",
                    help="Select the second AI model provider to use for generating responses.",
                    options=providers,
                    index=providers.index(st.session_state.model_provider_2)
                )
                if st.session_state.model_provider_2 == "Google Gemini":
                    st.session_state.gemini_model_2 = st.selectbox(
                        label="Gemini Model",
                        help="Select which Gemini model to use.",
                        options=gemini.models.keys()
                    )
                elif st.session_state.model_provider_2 == "Cloudflare Workers AI":
                    st.session_state.cloudflare_model_2 = st.selectbox(
                        label="Cloudflare Workers AI Model",
                        help="Select which Cloudflare Workers AI model to use.",
                        options=cloudflare.models.keys()
                    )
                elif st.session_state.model_provider_2 == "Cohere":
                    st.session_state.cohere_model_2 = st.selectbox(
                        label="Cohere Model",
                        help="Select which Cohere model to use.",
                        options=cohere.models.keys()
                    )
                elif st.session_state.model_provider_2 == "OpenRouter":
                    st.session_state.openrouter_model_2 = st.selectbox(
                        label="OpenRouter Model",
                        help="Select which OpenRouter model to use.",
                        options=openrouter.models.keys()
                    )
                elif st.session_state.model_provider_2 == "Groq":
                    st.session_state.groq_model_2 = st.selectbox(
                        label="Groq Model",
                        help="Select which Groq model to use.",
                        options=groq.models.keys()
                    )
    else:
        # Add system prompt input
        system_prompt = st.text_area(
            label="System Prompt",
            help="Set a system prompt that will be included at the beginning of each conversation. Leave empty for no system prompt.",
            value=st.session_state.system_prompt,
            placeholder="Example: You are a helpful assistant who specializes in programming...",
            height=100
        )
        # Update session state if the prompt has changed
        if system_prompt != st.session_state.system_prompt:
            st.session_state.system_prompt = system_prompt

        st.session_state.model_provider = st.selectbox(
            label="Model Provider",
            help="Select the AI model provider to use for generating responses.",
            options=["Local Model", "Google Gemini", "Cloudflare Workers AI", "Cohere", "OpenRouter", "Groq"],
            index=["Local Model", "Google Gemini", "Cloudflare Workers AI", "Cohere", "OpenRouter", "Groq"].index(st.session_state.model_provider)
        )
        
        # Add streaming toggle (only for Local Model)
        if st.session_state.model_provider == "Local Model":
            st.session_state.enable_streaming = st.toggle(
                label="Enable Streaming",
                help="Enable streaming responses that appear word by word instead of all at once.",
                value=st.session_state.enable_streaming
            )
        else:
            # Reset streaming to false when not using Local Model
            st.session_state.enable_streaming = False
        
        if st.session_state.model_provider == "Google Gemini":
            st.session_state.gemini_model = st.selectbox(
                label="Gemini Model",
                help="Select which Gemini model to use.",
                options=gemini.models.keys()
            )
        elif st.session_state.model_provider == "Cloudflare Workers AI":
            st.session_state.cloudflare_model = st.selectbox(
                label="Cloudflare Workers AI Model",
                help="Select which Cloudflare Workers AI model to use.",
                options=cloudflare.models.keys()
            )
        elif st.session_state.model_provider == "Cohere":
            st.session_state.cohere_model = st.selectbox(
                label="Cohere Model",
                help="Select which Cohere model to use.",
                options=cohere.models.keys()
            )
        elif st.session_state.model_provider == "OpenRouter":
            st.session_state.openrouter_model = st.selectbox(
                label="OpenRouter Model",
                help="Select which OpenRouter model to use.",
                options=openrouter.models.keys()
            )
        elif st.session_state.model_provider == "Groq":
            st.session_state.groq_model = st.selectbox(
                label="Groq Model",
                help="Select which Groq model to use.",
                options=groq.models.keys()
            )

    st.sidebar.markdown("## Generation Parameters")
    st.session_state.temperature = st.slider(
        label="Temperature", 
        help="Lower values generate more confident responses, while higher values generate more diverse and random responses.",
        min_value=0.0, 
        max_value=1.0, 
        value=0.7, 
        step=0.05)
    st.session_state.max_tokens = st.slider(
        label="Max Tokens",
        help="The maximum number of tokens to generate in the response.", 
        min_value=1024, 
        max_value=16384, 
        value=st.session_state.max_tokens,
        step=256)
    col1, col2, col3, col4, col5 = st.columns([1, 1, 1, 1, 1])
    with col1:
        if st.button(
            label="❌",
            help="Remove the previous user message and assistant response."):
            st.session_state.messages = st.session_state.messages[:-2]
            st.rerun()
    with col2:
        def edit_message():
            st.session_state.edit_mode = True
        # Edit last message
        st.button(
            label="✏️",
            help="Edit the last user message in the conversation history.",
            on_click=edit_message)
    with col3:
        if st.button(
            label="🔄️",
            help="Resubmit the previous message to get a new response."):
            st.session_state.messages = st.session_state.messages[:-1]
            response = get_text_to_text(progress_bar, message_placeholder)
            st.rerun()
    with col4:
        if st.button(
        label="🗑️",
        help="Start a new conversation."):
            st.session_state.messages = CHAT_DEFAULT.copy()
            st.session_state.usage_info = {}
            st.rerun()
    with col5:
        st.download_button(
            label="💾",
            help="Export the current conversations to a JSON file.",
            data=export_conversations(),
            file_name="conversations.json",
            mime="application/json"
        )
    with st.expander("Usage Info", expanded=False):
        st.markdown(f"Prompt Tokens: {st.session_state.usage_info.get('prompt_tokens', 'N/A')}")
        st.markdown(f"Completion Tokens: {st.session_state.usage_info.get('completion_tokens', 'N/A')}")
        st.markdown(f"Total Tokens: {st.session_state.usage_info.get('total_tokens', 'N/A')}")
                
    uploaded_file = st.file_uploader(
        label="Import Conversations",
        help="Import previous conversations from a JSON file to continue the chat.",
        type="json",
        key=st.session_state.chat_uploader_key,
        accept_multiple_files=False)
    if uploaded_file:
        import_conversations(uploaded_file)
        update_key("chat")
        st.rerun()
    
    upload_pdf = st.file_uploader(
    label = "Upload a PDF file", 
    help="Upload a PDF file to the chat. Only text content will be extracted from the PDF file.",
    type=["pdf"],
    accept_multiple_files=False,
    key=st.session_state.pdf_uploader_key)
    if upload_pdf:
        text = pdf_to_text(upload_pdf)
        st.session_state.messages.append({'role': 'user', 'type': 'PDF', 'file_name': upload_pdf.name, 'content': f"PDF File Content:\n\n{text}"})
        update_key("pdf")
        st.rerun()